export const FOTO_LIST_REQUEST = "FOTO_LIST_REQUEST";
export const FOTO_LIST_SUCCESS = "FOTO_LIST_SUCCESS";
export const FOTO_LIST_FAIL = "FOTO_LIST_FAIL";

export const FOTO_DETAILS_REQUEST = "FOTO_DETAILS_REQUEST";
export const FOTO_DETAILS_SUCCESS = "FOTO_DETAILS_SUCCESS";
export const FOTO_DETAILS_FAIL = "FOTO_DETAILS_FAIL";

export const FOTO_DELETE_REQUEST = "FOTO_DELETE_REQUEST";
export const FOTO_DELETE_SUCCESS = "FOTO_DELETE_SUCCESS";
export const FOTO_DELETE_FAIL = "FOTO_DELETE_FAIL";

export const FOTO_CREATE_REQUEST = "FOTO_CREATE_REQUEST";
export const FOTO_CREATE_SUCCESS = "FOTO_CREATE_SUCCESS";
export const FOTO_CREATE_FAIL = "FOTO_CREATE_FAIL";
export const FOTO_CREATE_RESET = "FOTO_CREATE_RESET";

export const FOTO_UPDATE_REQUEST = "FOTO_UPDATE_REQUEST";
export const FOTO_UPDATE_SUCCESS = "FOTO_UPDATE_SUCCESS";
export const FOTO_UPDATE_FAIL = "FOTO_UPDATE_FAIL";
export const FOTO_UPDATE_RESET = "FOTO_UPDATE_RESET";
